[package]
name = "Deposit"
version = "0.0.0"
authors = []

[addresses]
storage = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-framework", rev = "mainnet" }
